---
name: CI/CD
on:
  push:
    paths:
    - '.github/workflows/cicd.yml'
    - 'bin/*'
    - 'cf/**'
    - 'cmd/**'
    - 'templates/**'
    - '**Dockerfile'
    - 'Makefile*'
    - "run.sh"
    - "action.yml"
  workflow_dispatch:
  repository_dispatch:
    types: [update-cicd]

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    uses: jmpa-io/roots/.github/workflows/lint.yml@main
    secrets: inherit

  test:
    uses: jmpa-io/roots/.github/workflows/test.yml@main
    secrets: inherit

  test-action:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Test latest version of action.
      uses: ./
      with:
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  post-to-slack:
    needs: [lint, test, test-action]
    if: always()
    uses: jmpa-io/roots/.github/workflows/post-to-slack.yml@main
    secrets: inherit
